### ISSUE TITLE
Setting Volume in service: tts.speak or enable caching in action: media_player.play_media?

### ISSUE THREAD

**Issue by michis0806** [carleeno/elevenlabs_tts#163]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

I'm using eleven labs tts to announce some household issues (open window, rain ...) on my Sonos speakers depending on the occupancy of the rooms. I'm using the Sonos cloud integration as it works seamlessly with either idle or playing Sonos speakers. 
I tried both approaches, service: tts.speak and action: media_player.play_media but both have a shortcoming. 

1. With service: tts.speak I'm able to enable caching to save some credits with the api and reduce latency as the files are stored locally, but I did not manage to set the volume of the speakers as there is no volume parameter.
2. With action:media_player.play_media I was able to set the volume on the desired level but it's lacking the cache parameter.

Any ideas on that? Did anyone mange to set volume and caching?

Thanks
Michael 

### Describe the solution you'd like

I'd like to set caching and volume of the speakers in the calls

### Describe alternatives you've considered

I already considered setting the volume of the speakers before using service: tts.speak, but as there is some latency, playing speakers either decrease or increase the volume with the currently playing songs which is disturbing.

### Additional context

```
action: media_player.play_media
target:
  entity_id: media_player.move_2
data:
  media_content_id: >-
    media-source://tts/tts.elevenlabs_tts?message="{{message}}"&language=de&voice=otF9rqKzRHFgfwf6serQ
  media_content_type: provider
  extra:
    volume: 30
```

```
service: tts.speak
data:
  cache: true
  media_player_entity_id: media_player.move_2
  message: {{message}}
  options:
    voice: Julia
    stability: 1
    similarity: 1
    style: 0.3 # Only supported in eleven_multilingual_v2
    use_speaker_boost: "true" # Only supported in eleven_multilingual_v2
    model: eleven_multilingual_v2
    optimize_streaming_latency: 3
target:
  entity_id: tts.elevenlabs_tts
```
